# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
   


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pip3 install molecule[docker] yamllint ansible-lint

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: molecule test
